name: Build Cheetah
on: [ push, pull_request ]
jobs:
  build:
    env:
      BUILD_NUMBER: ${{ github.run_number }}

    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Set BUILD_STARTED_AT environment variable
        run: |
          echo "BUILD_STARTED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v4
      - if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # Allow cache writes on main and dev branches
          cache-read-only: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/heads/dev/') }}

      - name: Apply Patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew applyAllPatches --stacktrace

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Create Bundler Jar
        run: ./gradlew createBundlerJar --stacktrace

      - name: Upload Bundler Jar
        uses: actions/upload-artifact@v4
        with:
          name: cheetah-${{ env.BUILD_NUMBER }}
          path: cheetah-server/build/libs/cheetah-bundler-*.jar
          if-no-files-found: error
